/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Person__factory } from "./Person__factory";
export { Vaccination__factory } from "./Vaccination__factory";
